# Generated by Django 3.1.3 on 2020-12-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('turma', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('tipo_de_refeicao', models.IntegerField(choices=[(0, 'Jantar'), (1, 'Almoço')])),
                ('status', models.BooleanField()),
                ('alunos', models.ManyToManyField(related_name='forms', to='reifeicao.Aluno')),
            ],
        ),
    ]
